---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
paths:
  /v1/resources:
    post:
      operationId: create_resource
      description: Create a resource.
      responses:
        202:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceStatus'

components:
  schemas:
    ResourceStatus:
      description: The status of a create_resource operation
      properties:
        name:
          type: string
          description: The server-assigned name, which is only unique within the same service that originally returns it.
        done:
          type: boolean
          description: >-
            If the value is false, it means the operation is still in progress. If true, the operation is completed,
            and either error or response is available.
        result:
          description: >-
            The operation result, which can be either an error or a valid response. If done == false, neither error
            nor response is set. If done == true, exactly one of error or response is set.
          oneOf:
            - type: object
              properties:
                error:
                  $ref: '#/components/schemas/Error'
            - type: object
              properties:
                response:
                  $ref: '#/components/schemas/Resource'
      required:
        - name
        - done
        - result
      additionalProperties:
        description: >-
          Service-specific metadata associated with the operation. It typically contains progress information
          and common metadata such as create time. Some services might not provide such metadata. Any method that
          returns a long-running operation should document the additional properties that may be returned.
