---
name: lint
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Install prettier.
        run: npm install --global prettier
      - name: Verify proper formatting.
        run: prettier --check **/*.md **/*.md.j2
